"""Initial database schema

Revision ID: 5ec6405addd0
Revises:
Create Date: 2026-01-27 18:07:21.612898

"""
# pylint: disable=invalid-name,no-member,line-too-long
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5ec6405addd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema.

    Apply changes to move database schema forward.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('last_scanned_block', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', name='uq_chain_states_chain')
    )
    with op.batch_alter_table('chain_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chain_states_id'), ['id'], unique=False)

    op.create_table('hdwallet_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('index', sa.BigInteger(), nullable=False),
    sa.Column('is_swapped', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_chain'), ['chain'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=True),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=80, scale=0), nullable=False),
    sa.Column('status', sa.Enum('pending', 'detected', 'confirmed', 'paid', 'expired', 'settled', 'failed', name='paymentstatus'), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('detected_in_block', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', name='transactionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema.

    Revert changes to move database schema backward.
    Use with caution in production.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('payments')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_chain'))
        batch_op.drop_index(batch_op.f('ix_tokens_address'))

    op.drop_table('tokens')
    op.drop_table('hdwallet_addresses')
    with op.batch_alter_table('chain_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chain_states_id'))

    op.drop_table('chain_states')
    # ### end Alembic commands ###
